### ISSUE TITLE
Mistake in Vasicek definition?

### ISSUE THREAD

**Issue by FerPapi** [quantgirluk/aleatory#2]
Hi, I liked your package, thank you!

I believe there is a mistake in the Vasicek function

`def g(x, _):
            return self.sigma`

It should be

`def g(x, _):
            return self.sigma * x`

right?

**Comment by FerPapi** [comment]
Hi, just to comment further

As per the wikipedia article, https://en.wikipedia.org/wiki/Vasicek_model

what would actually be wrong is the documentation of the package

![image](https://github.com/quantgirluk/aleatory/assets/22220369/982ab002-b122-44b3-a3d7-6905d04c401f)

I'm not an expert, though, just trying to clarify it

Just a further suggestion, this could be modeled as `x**alpha` where alpha is set for each process modeled (in this case, alpha=0)

**Comment by quantgirluk** [comment]
Thanks for opening this issue and following up finding the typo the documentation.
The documentation has been fixed in 3420dcc commit 😊
